// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6gY-Jj8GVLVPiEZJoHkDBetB0obPdP4k',
    appId: '1:493964491999:web:642d5de1fe2eb9a8d87d6a',
    messagingSenderId: '493964491999',
    projectId: 'green-contribution-certificate',
    authDomain: 'green-contribution-certificate.firebaseapp.com',
    storageBucket: 'green-contribution-certificate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwIJXhurlTvCa3cM1f2SCpRxDbs5qyMIM',
    appId: '1:493964491999:android:99f2c84009122126d87d6a',
    messagingSenderId: '493964491999',
    projectId: 'green-contribution-certificate',
    storageBucket: 'green-contribution-certificate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_YliOXySaezlOYd_C-LqQTLIVjkr0HjQ',
    appId: '1:493964491999:ios:406582d13e7696cdd87d6a',
    messagingSenderId: '493964491999',
    projectId: 'green-contribution-certificate',
    storageBucket: 'green-contribution-certificate.firebasestorage.app',
    iosBundleId: 'com.gccltd.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_YliOXySaezlOYd_C-LqQTLIVjkr0HjQ',
    appId: '1:493964491999:ios:406582d13e7696cdd87d6a',
    messagingSenderId: '493964491999',
    projectId: 'green-contribution-certificate',
    storageBucket: 'green-contribution-certificate.firebasestorage.app',
    iosBundleId: 'com.gccltd.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6gY-Jj8GVLVPiEZJoHkDBetB0obPdP4k',
    appId: '1:493964491999:web:a79599fc6950a48cd87d6a',
    messagingSenderId: '493964491999',
    projectId: 'green-contribution-certificate',
    authDomain: 'green-contribution-certificate.firebaseapp.com',
    storageBucket: 'green-contribution-certificate.firebasestorage.app',
  );
}
